const Sequelize = require('sequelize');

const sequelize = new Sequelize({
  database: 'best_life_db',
  dialect: 'postgres',
  operatorsAliases: false,
  define: {
    underscored: true, // use underscored column names for columns generated by sequelize (e.g. timestamps as created_at rather than createdAt)
  }
});


const User = sequelize.define('user', {
  email: Sequelize.STRING,
  password: Sequelize.STRING,
  current_weight: Sequelize.INTEGER,
  goal_weight:Sequelize.INTEGER,
  calorie_intake: Sequelize.INTEGER
});

const Food = sequelize.define('food', {
  name: Sequelize.STRING,
  total_calories: Sequelize.INTEGER,
  date: Sequelize.DATE,
});

const Excercise = sequelize.define('excercise', {
  name: Sequelize.STRING,
  total_calories: Sequelize.INTEGER,
  date: Sequelize.DATE
});

User.hasMany(Food, {onDelete: 'cascade'});
User.hasMany(Excercise, {onDelete: 'cascade'});
Food.belongsTo(User);
Excercise.belongsTo(User);


module.exports = {
  sequelize,
  User,
  Food,
  Excercise
};
